version: '3.8'

networks:
  diplomski:
    driver: bridge

services:
  sqldb:
    image: mysql:8.0
    container_name: sqldb
    restart: "no"
    environment:
      MYSQL_DATABASE: 'diplomski'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3308:3306'
    expose:
      - '3306'
    volumes:
      - ./my-db:/var/lib/mysql
    networks:
      - diplomski
  marjan-jovanovic-be:
    container_name: marjan-jovanovic-be
    depends_on:
      - sqldb
    build: .
    environment:
      - SERVER_PORT=8080
      - SERVER_CONTEXT_PATH=/marjan-jovanovic-be/api
      - DB_HOST=sqldb
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=root
    restart: "no"
    ports:
      - 8080:8080
    networks:
      - diplomski